// Auto-generated by scripts/train_classifier.py
// Zero-dependency, deterministic real-time decision tree inference
#ifndef INTELLIGENCE_DOMAIN_MODEL_RULES_HPP_
#define INTELLIGENCE_DOMAIN_MODEL_RULES_HPP_

#include <cstdint>

namespace intelligence_domain
{

enum class TerrainVerdict : int32_t
{
  SAFE = 0,
  UNSAFE_SLOPE = 1,
  UNSAFE_VEGETATION = 2
};

/**
 * Feature mapping:
 * [0] mean_tof
 * [1] spatial_variance
 * [2] delta_d
 * [3] delta_d_variance
 * [4] beta_slope
 * [5] omega_norm
 * [6] tilt_error
 */
inline int32_t predict_terrain(const float * features)
{
  if (features[6] <= 0.137855f) {
    return 0; // SAFE
  } else {
    if (features[1] <= 0.000783f) {
      return 1; // UNSAFE_SLOPE
    } else {
      return 2; // UNSAFE_VEGETATION
    }
  }

}

}  // namespace intelligence_domain

#endif  // INTELLIGENCE_DOMAIN_MODEL_RULES_HPP_
