#!/usr/bin/env python3
import os
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, _tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

DATASET_PATH = 'data/dataset.csv'
OUTPUT_HEADER = 'src/intelligence_domain/include/intelligence_domain/model_rules.hpp'

FEATURE_NAMES = [
    'mean_tof',
    'spatial_variance',
    'delta_d',
    'delta_d_variance',
    'beta_slope',
    'omega_norm',
    'tilt_error'
]

CLASS_NAMES = ['SAFE', 'UNSAFE_SLOPE', 'UNSAFE_VEGETATION']

def export_tree_to_cpp(tree_model, feature_names, output_path):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    tree = tree_model.tree_

    def recurse(node, depth=1):
        indent = "  " * depth
        if tree.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_names[tree.feature[node]]
            idx = tree.feature[node]
            threshold = tree.threshold[node]
            cpp_code = f"{indent}if (features[{idx}] <= {threshold:.6f}f) {{\n"
            cpp_code += recurse(tree.children_left[node], depth + 1)
            cpp_code += f"{indent}}} else {{\n"
            cpp_code += recurse(tree.children_right[node], depth + 1)
            cpp_code += f"{indent}}}\n"
            return cpp_code
        else:
            class_idx = int(np.argmax(tree.value[node]))
            return f"{indent}return {class_idx}; // {CLASS_NAMES[class_idx]}\n"

    header_content = f"""// Auto-generated by scripts/train_classifier.py
// Zero-dependency, deterministic real-time decision tree inference
#ifndef INTELLIGENCE_DOMAIN_MODEL_RULES_HPP_
#define INTELLIGENCE_DOMAIN_MODEL_RULES_HPP_

#include <cstdint>

namespace intelligence_domain
{{

enum class TerrainVerdict : int32_t
{{
  SAFE = 0,
  UNSAFE_SLOPE = 1,
  UNSAFE_VEGETATION = 2
}};

/**
 * Feature mapping:
 * [0] mean_tof
 * [1] spatial_variance
 * [2] delta_d
 * [3] delta_d_variance
 * [4] beta_slope
 * [5] omega_norm
 * [6] tilt_error
 */
inline int32_t predict_terrain(const float * features)
{{
{recurse(0, 1)}
}}

}}  // namespace intelligence_domain

#endif  // INTELLIGENCE_DOMAIN_MODEL_RULES_HPP_
"""

    with open(output_path, 'w') as f:
        f.write(header_content)
    print(f"Exported C++ inference header to: {output_path}")

def main():
    if not os.path.exists(DATASET_PATH):
        raise FileNotFoundError(f"Dataset not found at {DATASET_PATH}. Run record_dataset.py first.")

    print(f"Loading dataset: {DATASET_PATH}")
    df = pd.read_csv(DATASET_PATH)

    X = df[FEATURE_NAMES].values
    y = df['label'].values.astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )

    clf = DecisionTreeClassifier(max_depth=4, random_state=42)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    print("\n--- Model Evaluation (Test Split) ---")
    print(classification_report(y_test, y_pred, target_names=CLASS_NAMES, digits=4))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    export_tree_to_cpp(clf, FEATURE_NAMES, OUTPUT_HEADER)

if __name__ == '__main__':
    main()
